### PR TITLE
Feat/share improvements

### PR DESCRIPTION
**Pull request by rasmuscnielsen**
- Added spinners during loading
- Added confetti @goldzulu  🎉 

I might need to tweak a few more things though as there are a few timing issues due slow CDN loads

### CODE REVIEW

**Comment by briangershon** [comment]
Thanks for working on the spinners -- mainnet and ipfs are pretty slow -- I just minted mine and it only took a couple of minutes to "claim", but also seemed like forever awaiting my IPFS preview.

**Comment by goldzulu** [comment]
Abit if a worry coz we are definitely not loaded up yet

**Comment by goldzulu** [comment]
Could we do a placeholder that is greyed out or a dimmed version while waiting for the final ipfs version to load or can the server cache the IPFS call? And warm up the cache by programmatically calling the ipfs endpoints?

**Comment by rasmuscnielsen** [comment]
@goldzulu So in this PR I introduced using 2 IPFS CDN's and have them race each other for faster loads. 

Further more I've now introduced a spinner + text. **Additionally**  it is now pulling the actual PNG via ajax and injects it directly into the `` so we can know exactly when the image is visible to the user and then fire off the confetti at that exact time. 

Here is a video 🎉  

https://user-images.githubusercontent.com/8465957/155005064-0ab28823-39c2-45e6-aaa2-dc7b709c8757.mov

In this case it loaded the image quite fast so the experience was good. I'll need to test it more to see if it behaves similar under all circumstances, but I believe we're good to merge this one now.

**Comment by rasmuscnielsen** [comment]
I'll go ahead and merge this one too

**Pull request merged**
