### PR TITLE
Fix incorrect flag for Pyongyang

### PR DESCRIPTION
**Pull request by xyzso0**
Before:
image

After:
image

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Hey! Thanks for spotting this. We should definitely address this. What I would suggest is having @eknobl take a look at this because we want to keep the theme of the designs consistent. :D

**Comment by xyzso0** [comment]
> Hey! Thanks for spotting this. We should definitely address this. What I would suggest is having @eknobl take a look at this because we want to keep the theme of the designs consistent. :D

ok great. I agree on the point of making the theme consistent, but I also want to point out that it should represent the flag of DPRK correctly. I appreciate your time and look forward to hearing from you, @eknobl

**Comment by eknobl** [comment]
Working on it. I'll update.

**Comment by rasmuscnielsen** [comment]
Submitted fix in PR #18 (png provided by @eknobl 🚀  )

**Pull request closed without merging**
