### PR TITLE
Link to this repo on the page #24

### PR DESCRIPTION
**Pull request by RAKESH32**
Adding Github link pointing to DAO repo.

### CODE REVIEW

**Review by Dhaiwat10 — CHANGES_REQUESTED** [review]
Hey, thanks for putting this in. I think you ran `npm install` instead of `yarn` which resulted in the `package-lock.json` file being added. Could you remove that file?

**Comment by RAKESH32** [comment]
removed package-lock.json

**Comment by Dhaiwat10** [comment]
Hey @RAKESH32, there was an extra `</div` on line 26 in `Preview.vue` introduced when resolving merge conflicts. It's causing the build to fail. Could you remove it pls? I tried doing it myself but I cannot commit for some reason.

**Comment by RAKESH32** [comment]
Thanks @Dhaiwat10  .Done

**Comment by Dhaiwat10** [comment]
Thanks @RAKESH32

**Pull request merged**
