### PR TITLE
UI / UX improvements before launch

### PR DESCRIPTION
**Pull request by rasmuscnielsen**
- Added modal for insufficient funds
- Added modal for no available genesis NFTs 
- Tweaked network modal to look less like an error and more like a "Hey, lets jump on to Polygon shall we" :-) 

Please feel free to make improvements to wording

Skærmbillede 2022-02-17 kl  22 25 23
Skærmbillede 2022-02-17 kl  22 25 44
Skærmbillede 2022-02-17 kl  22 26 14

### CODE REVIEW

**Comment by rasmuscnielsen** [comment]
closes #64

**Comment by rasmuscnielsen** [comment]
Also fixed #84 #64 #65 #26 🎉

**Comment by briangershon** [comment]
Thanks @rasmuscnielsen for all your work on this and tackling 4 issues!

So far, I've tested:
- [x] Mumbai Network Dialog box
- [x] No Available Genesis NFT box

I need to deploy a test contract to give the congratulations flow a try!

**Comment by rasmuscnielsen** [comment]
Implemented dark mode ! 🎉  Closes #67

**Comment by briangershon** [comment]
Hey @rasmuscnielsen I tested the full flow and successfully saw the congrats dialog! Worked well!

- [ ] Minor: I noticed that after success, the word "Unclaimed" was still present under the image. Hard-refresh fixes.

Screen Shot 2022-02-19 at 10 04 21 AM

- [ ] I found one bug in the dark mode while picking my token from the drop-down -- white text on light gray background, not enough contrast.

Screen Shot 2022-02-19 at 10 15 31 AM
 
- I noticed some Vue warnings in console when I first loaded the site, but probably nothing to worry about.

**Comment by rasmuscnielsen** [comment]
@briangershon Thanks for the feedback! I believe all these issues should be fixed in the most recent version :-)

**Pull request merged**
