### PR TITLE
Add automated tests for PixelAvatars Solidity contract

### PR DESCRIPTION
**Pull request by briangershon**
- Add automated tests for PixelAvatars Solidity contract with 100% test coverage. Remove old tests.
- Removed unused `_baseURI()` function from contract.
- Add test commands to `package.json`
- Updated README with testing instructions. (I only added `yarn test` lines, but ran prettier which changed some other lines)
- Add Github Actions to automatically run Solidity tests on push

Screen Shot 2021-12-29 at 5 46 45 PM

### CODE REVIEW

**Comment by briangershon** [comment]
Hey @rasmuscnielsen I made one change to the contract itself.

- [ ] Please double-check removing `_baseURI()` is ok.

Here's why I removed:

- I'm not able to directly test _baseURI() since there's already a public getter defined from the string public baseURI = ... so the code coverage marks the line uncovered.
- Function is currently unused in the code base and I think the public getter serves the same purpose.

**Comment by rasmuscnielsen** [comment]
Hey @briangershon 

This is really cool. Thanks for taking this on!

Regarding the _baseURI() I think it's used for the ERC721 extension.

At least I found these two snippets, so I think we gotta keep it on :-) 

image
image

____

Also I pushed your prettier fix on the folder-structure branch and re-ran the styling, so perhaps that will clean up this PR diff if you do a rebase? 
Hope it won't cause you too much trouble that I pushed that fix :-)

**Comment by briangershon** [comment]
Thanks @rasmuscnielsen -- no worries, I'll bring back the `_baseURI()`method. The code coverage report will show the line uncovered, but better the contract work than the coverage be perfect :-)

**Comment by rasmuscnielsen** [comment]
@briangershon Haha yes exactly! 

Oh and btw really cool that you added GH Actions! In case you missed it we also have this open issue #31. 

Any chance it would be an easy addition for you to run the styling scripts and commit any changes?

**Comment by briangershon** [comment]
Ok, `_baseURI()` is back!

Sure, I'll take a look at #31. I'll work on this in a separate PR so we can merge this one in. I haven't written a github action that modifies the repo, but seems like it should be doable.

**Comment by rasmuscnielsen** [comment]
Looks good - will merge!

**Pull request merged**
